openai:
  api:
    key: ${openai-key}
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: torquemada
#    password: surgery
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/smartcv;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS smartcv
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: development
    default-schema: smartcv
    drop-first: false       # Set to true only if you want to drop all tables first (for dev)
    parameters:
      schema: smartcv
